language: java
jdk:
  - oraclejdk8

stages:
  - name: build
    if: NOT tag IS present
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      script: "./mvnw clean verify -P coverage-report"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      script: "./mvnw release:clean release:prepare release:perform --settings .travis/settings.xml"

deploy:
  provider: bintray
  on:
    tags: true
  file: .travis/bintray-deploy.json
  user: boereck
  dry-run: true
  key:
    secure: HWs98/0DRpmQxq1S0Zp37K3EFttg63ty6HqCn+iDOF0epIcFGZzuUBA2Web3/QpRd1r41zAz5CaiHmyAPPLBF3KgivvhOWRjEZKlIkwg2osNWETTA9kbADH0TaVB9pJA26yn0ILV3vLT/sRt3fx/Vs44NcInV88ChrjiujYw0ivUKVaE+YZqUQqfEFjVBNWtpJdgiwAdSY+ZYQg/O3XRRnhgo/QTHuk/yQ3scJykpIJ300K5ifidXT6mzPGjybp7Ixx6y+wkOisXMVY8ICVi4w0ZMnNih4TuM4pnZnWU9a1Oyt1gnltmG026ItP9fBOs+UDdiADZt2LSQ8KfPigyFl2K0YNJXvirMOiC3yR8/utcPx97JU7u7MJ6mCyooBheBw0xfmSVduKLlvLToC/PW83K4k2TeS4tn50Iluj/7wBBVo0Ad+lKdcMrPuECE50txa7KM73YvjyFgAWqvdGkl91XcBSOAFld7tsY+TYkqHTqx+ya6uUzDLVK2Zfpefm02xkCZycSyQUUIR0Io5Qv9SKXw9sTUmSulgGUAhvsg0Omfpvp1WxEkhK7nLuE2FX584B/3A+vL5cQ3yVyb5q+LHN5JVECVvlo4UIPeZnAe2anrJtV6Gu1+dHxqiGvcmikRkqIFu/0kbWQ9YIlk/oCJPtd/M6Xw5DMoncdgiHyoXY=
